name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: echo /home/linuxbrew/.linuxbrew/bin >> $GITHUB_PATH
      - run: brew install zig
      - run: zig build test --summary new
